project:
  type: website
  output-dir: docs
  resources:
    - CNAME
  
website:
  title: ""
  navbar:
    left:
      - href: pages/daniel_allman.qmd
        text: Daniel Allman
    right:
      - href: pages/projects.qmd
        text: Projects
      - href: pages/photos.qmd
        text: Photos
      - href: pages/photos.qmd
        text: Contact
    tools:
      - icon: mortarboard
        href: https://scholar.google.com.au/citations?view_op=list_works&hl=en&user=EJzZvOYAAAAJ&gmla=AIfU4H76cl-gMSFa6zlgdAhH02pVZVMqxO4gnIpnafhIses84Bxx6BBCA4xEdmc-Gj7XbaAxlbUM8f3oSQK_nN3ZKM0cmALZ-ZTPsFHeshgHk34u_TtS
      - icon: person-circle
        href: https://orcid.org/0009-0000-2249-
        target: _blank
      - icon: linkedin
        href: 
        
        <a href="https://doi.org/10.25949/26793253.v1" target="_blank">Master of Research thesis</a>

  page-footer:
    right: "&copy; Copyright 2025, Daniel Allman"

format:
  html:
    theme: simplex

editor: source



