project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  title: "Daniel Allman"
  search: false
  navbar:
    pinned: true
    logo: pages/images/ant_jump.jpg
    logo-href: daniel_allman.qmd
    right:
      - href: pages/projects.qmd
        text: Projects
      - href: pages/photos.qmd
        text: Photos
      - href: pages/contact.qmd
        text: Contact

      - icon: mortarboard
        href: https://scholar.google.com.au/citations?view_op=list_works&hl=en&user=EJzZvOYAAAAJ&gmla=AIfU4H76cl-gMSFa6zlgdAhH02pVZVMqxO4gnIpnafhIses84Bxx6BBCA4xEdmc-Gj7XbaAxlbUM8f3oSQK_nN3ZKM0cmALZ-ZTPsFHeshgHk34u_TtS
        target: _blank
      - icon: person-circle
        href: https://orcid.org/0009-0000-2249-2841
        target: _blank
  page-footer:
    right: "&copy; Copyright 2025, Daniel Allman"

format:
  html:
    theme: simplex

editor: source



